### PR TITLE
Document cli commands

### PR DESCRIPTION
**Pull request by khaya-zulu**
Screenshot 2022-05-23 at 17 00 33

### Added

Create a single page for cli reference.

### Format

# `Command`

<Description>

## `action`

**Description**

**Command Args**

**Command Flags**

### CODE REVIEW

**Comment by peterp** [comment]
This is awesome, can you make the CLI reference the top-level? E.g.: When I click on "CLI Reference" it just shows me the page and not a drop-down option?

And if so then you can delete introduction.

**Comment by peterp** [comment]
With the restore command I think `--db-name` and `--new` are deprecated:
image

**Comment by peterp** [comment]
The `restore` command has an alias of `r`
image

**Comment by peterp** [comment]
Let's remove the colons`:` for the top-level objects and make them back-tick escaped, then `proxy` will also make a bit more sense:

image

**Comment by peterp** [comment]
Let's hide debug, it's a hidden command
image

**Review by peterp — CHANGES_REQUESTED** [review]
Super close, just a few changes come due.

**Comment by peterp** [comment]
The new navigation is collapsed by default, can you make them expanded
image

**Comment by peterp** [comment]
Could you make the main sections lowercase? `auth`, `config`, etc...

image

**Comment by peterp** [comment]
Also, could you take the alias part out of the title and rather add that as a section in the action reference?

**Review by peterp — CHANGES_REQUESTED** [review]
A few more stylistic things

**Comment by khaya-zulu** [comment]
Screenshot 2022-05-25 at 10 08 13

**Review by peterp — APPROVED** [review]

**Pull request merged**
