### PR TITLE
Remove examples and upcoming integrations sections

### PR DESCRIPTION
**Pull request by sudoramz**
Remove sections: examples and upcoming integrations

### CODE REVIEW

**Review by peterp — CHANGES_REQUESTED** [review]
Can we move the files somewhere? but not display them, I think they would help as a reference for future documentation writers.

**Comment by sudoramz** [comment]
Wouldn't they technically always be on this repo so we could always reference them from here? In addition to this, we could have them sit on Notion?

**Comment by peterp** [comment]
Yeah, technically true, but practically I don't think I've seen anyone look through git history in order to find something that they would not know exists.

**Comment by sudoramz** [comment]
Fair enough. Can we pop them on Notion? Alternatively, let me check Docasaurus and see if there is a property you can set on the config object in `_category_.json` to essentially hide a given folder.

**Comment by sudoramz** [comment]
We will have to put it on Notion. And create maybe a folder of 'removed documentation'. If that's fine, let me know and I will get it done ASAP.

**Comment by peterp** [comment]
I'm sure Docusaurus has a search path, maybe we can just move them outside of that.

**Pull request closed without merging**
